### ISSUE TITLE
Crash after update to version 74.4.1 (performed by F-Droid)

### ISSUE THREAD

**Issue by gerryfrancis** [Tobi823/ffupdater#81] opened 2021-09-29 21:29 UTC
java.lang.RuntimeException

Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException

java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7664)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.NetworkOnMainThreadException
  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
  at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
  at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
  at java.net.InetAddress.getByName(InetAddress.java:1106)
  at de.marmaro.krt.ffupdater.download.NetworkUtil.isDnsResolvable(NetworkUtil.kt:54)
  at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:32)
  at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:18)
  at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetUnavailable(NetworkUtil.kt:22)
  at de.marmaro.krt.ffupdater.MainActivity.checkForUpdates(MainActivity.kt:186)
  at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:94)
  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
  at android.app.Activity.performResume(Activity.java:8129)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
  ... 12 more

Fairphone FP2, Android 11 (lineage_FP2-userdebug 11 RQ3A-210905.001 10035319)

**Comment by Tobi823** [comment] 2021-09-29 21:47
Should be fixed in version 74.4.3. 

You can either wait for the release on F-Droid (next days), use my F-Droid repository or download the APK file (see https://github.com/Tobi823/ffupdater#other-distribution-channels)

**Comment by d4f5409d** [comment] 2021-09-30 12:48
Same problem

java.lang.RuntimeException
-
Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
-
java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: android.os.NetworkOnMainThreadException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4631)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4663)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getByName(InetAddress.java:1106)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isDnsResolvable(NetworkUtil.kt:54)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:32)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetAvailable(NetworkUtil.kt:18)
	at de.marmaro.krt.ffupdater.download.NetworkUtil.isInternetUnavailable(NetworkUtil.kt:22)
	at de.marmaro.krt.ffupdater.MainActivity.checkForUpdates(MainActivity.kt:186)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:94)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1571)
	at android.app.Activity.performResume(Activity.java:8141)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4621)
	... 12 more

**Comment by Nickoriginal** [comment] 2021-09-30 18:02
https://github.com/Tobi823/ffupdater/issues/80

**Comment by Nickoriginal** [comment] 2021-09-30 18:07
It was reported before by me. Closing it was my mistake, because otherwise people would not create duplicates, would know about the problem, developer's answer and solution earlier.

**Comment by goodevilgenius** [comment] 2021-10-01 00:42
Same issue.

I tried downloading  74.4.3 from Git lab, but it refused to install.

Added your F-Droid repo, but after updating repos, no update showed up.

**Comment by gerryfrancis** [comment] 2021-10-01 11:16
@goodevilgenius I think your issue is a different one, please reread my description. Thanks.

**Comment by Nickoriginal** [comment] 2021-10-01 11:40
https://github.com/Tobi823/ffupdater/issues/81#issuecomment-931804305
idk about the Google Play version, but F-Droid version is not compatible with any other (due to signature) and should be uninstalled before installing any other version.

**Comment by goodevilgenius** [comment] 2021-10-01 11:52
@gerryfrancis I've got 74.4.1 installed. I have the same error. I was unable to install  74.4.3 as @Tobi823 said would fix the issue.

**Comment by goodevilgenius** [comment] 2021-10-01 11:55
> [#81 (comment)](https://github.com/Tobi823/ffupdater/issues/81#issuecomment-931804305) idk about the Google Play version, but F-Droid version is not compatible with any other (due to signature) and should be uninstalled before installing any other version.

That makes sense, @Nickoriginal but is unfortunate. If I want to upgrade using another method, I won't be able to switch back to F-Droid with future versions without uninstalling first.

I guess I'll have to wait.

**Comment by Nickoriginal** [comment] 2021-10-01 15:46
Now you should not wait - it is available now in the F-Droid! Missing app icon in the F-Droid was fixed, as well as crash. Good job @Tobi823!

**Comment by Nickoriginal** [comment] 2021-10-01 15:50
> If I want to upgrade using another method, I won't be able to switch back to F-Droid with future versions without uninstalling first.
Well, this is a inconvenient property of absolutely all applications installed from the native F-Droid repository, so you should pay attention for this when using F-Droid.

**Comment by Tobi823** [comment] 2021-10-01 21:32
> Now you should not wait - it is available now in the F-Droid!

@Nickoriginal thanks for the update.

I'm closing this issue now.

**Closed by Tobi823** 2021-10-01 21:32 UTC
Labels: fix will be soon available on F-Droid
