### ISSUE TITLE
Recurring crash with Firefox Nightly

### ISSUE THREAD

**Issue by bet** [Tobi823/ffupdater#40] opened 2021-04-29 14:17 UTC
I'm seeing this on a Nexus 6 running LineageOS 17.1

Here's the trace:

java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.FirefoxNightly.getDisplayInstalledVersion(FirefoxNightly.kt:38)
	at de.marmaro.krt.ffupdater.MainActivity.initUI(MainActivity.kt:129)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:82)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7958)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more

I'm only reporting in case this might be a problem unrelated to my weird platform. But if you want to just mark this closed because there's no chance you can reproduce it, I understand.

**Comment by Tobi823** [comment] 2021-04-29 14:46
Which version of FFUpdater are you using? 73.1.2, 73.1.1, ... ?

**Comment by bet** [comment] 2021-04-29 14:53
I don't know what I had before the first uninstall, but f-droid is offering 73.1.1, that's what I just reinstalled and it crashed immediately on trying to open it.

**Comment by bet** [comment] 2021-04-29 15:03
And I just tried running it (same release) on my other phone, a Pixel 3 running stock OS, and it crashed. Seems like 73.1.1 has a fatal disagreement with the environment.  Fresh crash from my Pixel 3:

java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.FirefoxNightly.getDisplayInstalledVersion(FirefoxNightly.kt:38)
	at de.marmaro.krt.ffupdater.MainActivity.initUI(MainActivity.kt:129)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:82)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8135)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
	... 12 more

**Comment by Tobi823** [comment] 2021-04-29 15:29
I've discovered the problem. The structure of the version name of Firefox Nightly has changed.

FFUpdater expects something like "Nightly 210428 17:01" but it's now "90.0a1". https://www.apkmirror.com/apk/mozilla/firefox-fenix/

**Comment by bet** [comment] 2021-04-29 15:32
Thank you! I can confirm that uninstalling Firefox Nightly fixed the crash for me.

**Comment by Tobi823** [comment] 2021-04-29 15:56
Temporary workaround until I can fix the real problem: Delete Firefox Nightly

**Comment by adnansumi98** [comment] 2021-05-05 08:22
java.lang.RuntimeException at FirefoxNightly.kt:38
java.lang.RuntimeException

java.lang.RuntimeException: Unable to resume activity {de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4398)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4430)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.NullPointerException
	at de.marmaro.krt.ffupdater.app.impl.FirefoxNightly.getDisplayInstalledVersion(FirefoxNightly.kt:38)
	at de.marmaro.krt.ffupdater.MainActivity.initUI(MainActivity.kt:130)
	at de.marmaro.krt.ffupdater.MainActivity.onResume(MainActivity.kt:83)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1475)
	at android.app.Activity.performResume(Activity.java:7959)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4388)
	... 11 more


Android Version: 29
Device Manufacturer: motorola
Device Model: motorola one fusion+


Hi
Thanks for making FFupdater 
I am also facing issie with firefox Nightly
I did uninstall it and mark it as excluded application
It will fix the issue for now
Please fix as soon as possible
Thanks again

**Comment by absolutez3** [comment] 2021-05-07 06:17
+1

**Comment by Tobi823** [comment] 2021-05-07 12:20
It's now fixed in version "71.1.3". Should be available soon on F-Droid.

**Closed** 2021-05-29 13:19 UTC
Labels: fix will be soon available on F-Droid
