### ISSUE TITLE
Crash on starting app

### ISSUE THREAD

**Issue by WPTP** [Tobi823/ffupdater#492] opened 2023-09-08 19:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error message from FFUpdater**
Please copy and paste the error message with the stacktrace and error log here:

**Comment by Tobi823** [comment] 2023-09-08 22:01
Duplicate of https://github.com/Tobi823/ffupdater/issues/491

**Closed by Tobi823** 2023-09-08 22:01 UTC
