### ISSUE TITLE
Firefox nightly updates infinitely

### ISSUE THREAD

**Issue by Sayori1576** [Tobi823/ffupdater#148] opened 2022-04-25 22:23 UTC
Stacktrace:
```
java.lang.IllegalArgumentException: File '/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/files/Download/org.mozilla.fenix.apk' must exists.
	at de.marmaro.krt.ffupdater.security.FingerprintValidator.checkApkFile(Unknown Source:87)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.secureInstallAsync(Unknown Source:116)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller.access$secureInstallAsync(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SecureAppInstaller$installAsync$2$1.invokeSuspend(Unknown Source:30)
	at q3.a.resumeWith(Unknown Source:8)
	at e4.f0.run(Unknown Source:86)
	at h4.a.q(Unknown Source:0)
	at h4.a$a.run(:5)
```
Device information:
| key | value |
| --- | --- |
| version name | 75.4.0 |
| version code | 98 |
| build type | release |
| SDK version | 29 |
| android release | 10 |
| board | exynos9810 |
| brand | samsung |
| device | starlteks |
| manufacturer | samsung |
| model | SM-G960N |
| product | starlteks |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1627344792000 |

**Comment by Tobi823** [comment] 2022-04-26 16:19
How often does the error occur? every time you want to install the browser or only rarely?

**Comment by Tobi823** [comment] 2022-04-26 17:08
Can you try this version?
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8565369/ffupdater-release.zip)

Maybe it is the same problem in #150

**Comment by Tobi823** [comment] 2022-04-26 18:55
#150 is fixed with this version. Does this work for you too? https://github.com/Tobi823/ffupdater/files/8565963/ffupdater-release.zip

**Comment by Sayori1576** [comment] 2022-04-27 06:48
No, The download percent is randomly changed.

**Comment by Tobi823** [comment] 2022-04-27 07:53
Sry, I have change the title of the wrong issue.

Can you send me screenshots of the problem? (Make sure that you use this version https://github.com/Tobi823/ffupdater/files/8565963/ffupdater-release.zip)

**Comment by Sayori1576** [comment] 2022-04-27 10:43
https://user-images.githubusercontent.com/93511899/165501160-3674e579-8f86-4301-b7c1-d632b4583890.mp4

Here is.

**Comment by Tobi823** [comment] 2022-04-28 20:03
Should be fixed in the current version 75.4.2 - can you verify it?

I think the "download percent randomly changed" was caused by:
- BackgroundJob is started and downloads Firefox Nightly
- BackgroundJob is restarted and downloads Firefox Release. FFUpdater has signaled the previous BackgroundJob to stop but it keeps downloading Firefox Nightly.

If the problem still exists, please reopen this issue.

**Comment by Sayori1576** [comment] 2022-04-29 11:47
![Screenshot_20220429-204633_FFUpdater.jpg](https://user-images.githubusercontent.com/93511899/165938561-bca7e511-31d3-4a8a-aac1-37941b170c7d.jpg)
What is that bug? I can't install any browser.

**Comment by Tobi823** [comment] 2022-04-29 12:29
I thought that the creator of the ticket can reopen it at any time - but I was wrong. https://stackoverflow.com/a/21333938

**Comment by Tobi823** [comment] 2022-04-29 12:52
Strange ... can you go to settings, disable the update check and enable it again?

This will restart the background update checker. Maybe this will help.

**Comment by Sayori1576** [comment] 2022-04-29 14:24
No, At Some percent, the percent was repeated to 0.

**Comment by Tobi823** [comment] 2022-05-01 20:14
I don't know why it does not work. Maybe the old method (using the offical Android DownloadManager) works better? Can you try it out?

**Comment by Tobi823** [comment] 2022-05-01 20:15
[ffupdater-release.zip](https://github.com/Tobi823/ffupdater/files/8599664/ffupdater-release.zip)

**Comment by Sayori1576** [comment] 2022-05-03 17:42
Sorry, I think it is root installer's error. When I off it, The error doesn't occured

**Comment by Tobi823** [comment] 2022-06-14 10:38
Does the error always occur or only irregularly?

Can you record your screen and show how the bug happens?

**Comment by Sayori1576** [comment] 2022-06-14 14:15
Always occures, and i will upload soon

**Comment by Sayori1576** [comment] 2022-06-16 09:54
I couldn't take a screenshot. The symptom is same to before.

**Comment by Tobi823** [comment] 2022-06-19 17:10
Try version 75.5.3 - the bug should be fixed now

**Comment by Sayori1576** [comment] 2022-06-20 10:23
No, the download percent is fixed by Specific percent.

**Comment by Sayori1576** [comment] 2022-06-20 10:32
Not fixed at all.

**Comment by Tobi823** [comment] 2022-06-28 21:35
Sorry, but I have no idea how I can fix this problem. 

Possible (but not perfect) workaround: You can disable the background download of updates in the settings. Then you will only get the info that there is an update and the error will not be triggered.

**Closed by Tobi823** 2022-06-28 21:35 UTC
