### ISSUE TITLE
FFupdater download duplicated

### ISSUE THREAD

**Issue by Redpillbug** [Tobi823/ffupdater#25] opened 2021-02-13 07:18 UTC
When the user attempts to update via pressing a notification triggered by the automatic check in background, Android's download manager indicates 2 downloads in progress, not one.
Other than this I realized the download time seems to be longer than usual, So I believe this isn't a issue from Android's download manager, and there is actually 2 downloads in progress.
However, this issues doesn't occur when the application is active(on screen) and it downloads just 1 file for update even when the user updates via pressing the notification.
This is not a issue that happens rarely, I use Firefox nightly, therefore I experienced this issue every time I tried to update by just pressing the update notification.

**Comment by Tobi823** [comment] 2021-02-14 23:49
That's strange - the download should only be triggered once.

Can you check if the issue is still present in version 71.0.0? (Should be available on F-Droid in the next days)

**Comment by Tobi823** [comment] 2021-02-18 17:59
The bug should be fixed in version 71.0.2

**Closed by Tobi823** 2021-02-18 17:59 UTC

**Comment by Redpillbug** [comment] 2021-02-20 15:07
Thank you! (I was about to send a reply to confirm this issue does happen on other android versions)
will this update roll out on f-droid in few days?
-------- Original Message --------

**Comment by Tobi823** [comment] 2021-02-21 12:26
I've forgotten to release the version 71.0.2 (more precisely I've forgotten to create a new Git tag. F-Droid checks my Git repository  for new Git tags regularly).

https://github.com/Tobi823/ffupdater/commit/1f4c1ca3c95dd28798ca00e341fec092808ce9f5

I think that the new version should be available in the next days.

There are three steps in F-Droid:
1. F-Droid must detect my Git tag. If a new Git tag is detected, the https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.marmaro.krt.ffupdater.yml will be updated
2. F-Droid must build my app. Go to https://f-droid.org/wiki/page/de.marmaro.krt.ffupdater and click on the "buildlog" link to see the last build time.
3. A F-Droid developer must signed the app and release it. Can take couple hours or 1/2 days.
