### ISSUE TITLE
[Bug]: ffupdater no longer automatically updates apps because they were "not installed by ffupdater" when they were installed by ffupdater

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [Tobi823/ffupdater#552] opened 2023-12-08 17:02 UTC
**Important first questions**

1. Is your FFUpdater up-to-date? If not, please abort and update FFUpdater.
Yes, I made sure to update ffupdater before making this

3. Do you spot similar issues in https://github.com/Tobi823/ffupdater/issues? If yes, please abort and add your error message as a comment to the existing issue.
No, I don't think there is an issue similar to this.

**Describe the bug**
When I install an app using ffupdater, then I tap the little i, it says that the app wasn't installed by ffupdater, so automatic updates are disabled. This is not true, since they were installed by ffupdater (through the shizuku installer). What's worse, I'm not getting any notifications from ffupdater about app updates.

**To Reproduce**
Please insert the steps to reproduce the behavior here:
1. Install an app through ffupdater. I don't know if the shizuku installer is needed, but it might be.
2. Tap on the i in the app card, and see that it says that automatic updates are disabled "because it wasn't installed by ffupdater".

**Expected behavior**
Please give a clear and concise description of what you expected to happen.
I would expect it to update my apps. I also think it would be good if ffupdater allowed me to choose to allow automatic updates, even if it says that my app wasn't installed using ffupdater.

**Comment by Tobi823** [comment] 2023-12-10 17:59
In the app card, can you click on "Install latest version"? Installing the latest update should mark the app as installed by FFupdater.

**Comment by ego-lay-atman-bay** [comment] 2023-12-10 18:30
That's what I did, but it didn't mark it as installed by ffupdater

**Comment by Tobi823** [comment] 2023-12-11 21:03
I guess I have to add an option to bypass the "update only if app was installed by FFUpdater" check. Next week I should have time for it :)

**Comment by Tobi823** [comment] 2023-12-11 21:04
Which smartphone and Android version are you using? With my Pixel 3a + GrapheneOS I was not able to reproduce your problem.

**Comment by ego-lay-atman-bay** [comment] 2023-12-11 21:10
I am using a google pixel 6a on android 14. I am also using shizuku to install the apps.

**Comment by Tobi823** [comment] 2023-12-11 21:52
My bad - I was able to reproduce your error but I did not recognize it

**Comment by Tobi823** [comment] 2023-12-11 21:53
Bug should be now fixed and will be part of the next release

**Comment by ego-lay-atman-bay** [comment] 2023-12-11 22:23
Are you sure that's the correct build, because that's version 79.1.0

**Comment by ego-lay-atman-bay** [comment] 2023-12-12 00:01
Ah, well it looks like nothing changed, but since there's no updates available, I don't know if it is actually fixed.

**Comment by ego-lay-atman-bay** [comment] 2023-12-14 18:09
Alright, after updating brave with ffupdater, I can safely say that it detects it as installed by ffupdater.

**Comment by ego-lay-atman-bay** [comment] 2023-12-16 01:11
Oh, I did not know that. That's pretty interesting.

Oh, also I noticed that the google play store has been showing updates for apps I installed through other apps (brave from ffupdater, anysoftkeyboard from f-droid (or droid-ify, etc.).

**Comment by ego-lay-atman-bay** [comment] 2023-12-21 03:44
I forgot to mention, I was able to auto update, I just got the notification that it was downloading brave, and so I waited, and then it showed the notification that it installed. It all happened without opening the app. I can safely say that the issue is fixed, and auto updating works perfectly.

**Closed** 2024-03-24 16:43 UTC
Labels: bug, fixed and will soon be released
