### ISSUE TITLE
App crash on brave update

### ISSUE THREAD

**Issue by Kurty00** [Tobi823/ffupdater#153] opened 2022-04-27 21:26 UTC
Stacktrace:
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=de.marmaro.krt.ffupdater.installer.ForegroundSessionInstaller.app_installed flg=0x10 pkg=de.marmaro.krt.ffupdater (has extras) } in de.marmaro.krt.ffupdater.installer.SessionInstallerBase$registerIntentReceiver$1@c2d2a9a
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.app.PendingIntent$CanceledException
	at android.app.PendingIntent.send(PendingIntent.java:880)
	at android.app.PendingIntent.send(PendingIntent.java:692)
	at de.marmaro.krt.ffupdater.installer.ForegroundSessionInstaller.requestInstallationPermission(Unknown Source:67)
	at de.marmaro.krt.ffupdater.installer.SessionInstallerBase.handleAppInstallationResult(Unknown Source:35)
	at de.marmaro.krt.ffupdater.installer.SessionInstallerBase.access$handleAppInstallationResult(Unknown Source:0)
	at de.marmaro.krt.ffupdater.installer.SessionInstallerBase$registerIntentReceiver$1.onReceive(Unknown Source:2)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
	... 8 more
Timestamp: 2022-04-27T23:25:19.401

```
Device information:
| key | value |
| --- | --- |
| version name | 75.4.1 |
| version code | 99 |
| build type | release |
| SDK version | 29 |
| android release | 10 |
| board | sdm845 |
| brand | OnePlus |
| device | OnePlus6 |
| manufacturer | OnePlus |
| model | ONEPLUS A6003 |
| product | OnePlus6 |
| SOC manufacturer | / |
| SOC model | / |
| supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| tags | release-keys |
| build time | 1626184838000 |

**Comment by Tobi823** [comment] 2022-04-27 22:06
I have a strong suspicion as to what the problem is. In version 75.4.1 I try to make the session installer more secure.

I had the suspicion that it can not run on some device - but was of the opinion that I am too pessimistic.

Will be fixed in 75.4.2

**Closed** 2022-04-27 22:21 UTC
