### ISSUE TITLE
Crash while downloading chromium

### ISSUE THREAD

**Issue by EricRC1627** [Tobi823/ffupdater#350] opened 2023-02-24 08:12 UTC
Stacktrace:
```
java.lang.IllegalArgumentException: Failed requirement.
	at de.marmaro.krt.ffupdater.installer.ApkChecker$Companion.throwIfApkFileIsNoValidZipFile(ApkChecker.kt:17)
	at de.marmaro.krt.ffupdater.DownloadActivity.startDownload(DownloadActivity.kt:330)
	at de.marmaro.krt.ffupdater.DownloadActivity.access$startDownload(DownloadActivity.kt:58)
	at de.marmaro.krt.ffupdater.DownloadActivity$startDownload$1.invokeSuspend(DownloadActivity.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ab7a511, Dispatchers.Main]
Timestamp: 2023-02-24T03:09:24.415

```
Device information:
| Key | Value |
| --- | --- |
| FFUpdater version | 77.7.6 (132) release |
| Device | SM-G998U (p3qsqw, p3q, lahaina) |
| Manufacturer | samsung (samsung) | 
| Supported ABIs | arm64-v8a, armeabi-v7a, armeabi |
| Android version | 13 (SDK: 33) |
| OS | 21DKGA06, dpi, release-keys, 1673353360000 |

**Comment by Wojtaz0w** [comment] 2023-02-24 12:58
This is a duplicate of #340
Please close 🙂

**Closed** 2023-02-24 17:26 UTC

**Comment by EricRC1627** [comment] 2023-02-24 17:28
Duplicate of #340
